baseurl = "https://punchingkitty.com"
url = "https://punchingkitty.com/"
DefaultContentLanguage = "en"
name = "Punching Kitty"
title = "PUNCHING KITTY"
description = "The gossip site St. Louis has always deserved!"
theme = "beautifulhugo"
googleAnalytics = "UA-7451307-1"

[Params]
  logo = "pk_logo.png"
  subtitle = "The gossip site St. Louis has always deserved!"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Media"
    url = "/categories/media"
    weight = 3

[[menu.main]]
    name = "Crime"
    url = "/categories/crime"
    weight = 3

[[menu.main]]
    name = "Sports"
    url = "/categories/sports"
    weight = 3

[[menu.main]]
    name = "Politics"
    url = "/categories/capitalism-and-politics"
    weight = 3

[[menu.main]]
    name = "More"
    url = "/categories/"
    weight = 4